---
- name: Installing and Managing Nginx Server 
  hosts: all   
  become: True
  vars:
    nginx_html: /usr/share/nginx/html
    user_home: .
    index_html: index.html
  tasks:
    - name: Install the latest version of nginx
      command: yum install nginx -y

    - name: Start nginx service
      service:
        name: nginx
        state: started

    - name: Enable nginx service
      service:
         name: nginx
         enabled: yes
    - name: Copy index.html to managed nodes
      copy:
        src:  "{{ user_home }}/{{ index_html }}"
        dest: "{{ nginx_html }}"