plugin: aws_ec2
regions:
  - us-east-1
keyed_groups:
  # - prefix: arch
  #   key: 'architecture'
  # - prefix: tag
  #   key: 'tags'
  # - key: instance_type
  #   prefix: instance_type
  - key: tags.key_name
    separator: ''