version: '3.8'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'user'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
  container_adminer:
    depends_on:
      - db
    image: adminer
    ports:
      - 8080:8080

# http://localhost:8080
# System : MySQL
# Server : db (container name)
# Usernam : user (root for admin)
# Password : user (root for admin)
# Database :  db

# 
# If not defined HOST PORT
# docker run -it --rm mysql mysql -h[CONTAINER_PRIVATE_ID] -uroot -proot
# After defined HOST PORT
# docker run -it --rm mysql mysql -h[USER_MACHINE_IP] -uroot -proot