---
- hosts: qa
  tasks:
   - name: Kernal
     debug: msg="{{ ansible_kernel }}"
   - name: Hostname
     debug: msg="{{ ansible_hostname }}"
   - debug: var=ansible_distribution
   - debug: var=ansible_bios_date
   - debug: var=ansible_env.HOME
   #- debug: var=hostvars (Same info with the cmd -  ansible qa -m setup >> vm_info )