name: 5_var_3_accessing_between_job

on: workflow_dispatch
env:
  env_var: ${{ vars.ENV_CONTEXT_VAR }}  # Access configuration variables

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Generate value
        id: step1
        run: echo "::set-output name=my_var::Hello World"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Use value from job1
        run: echo "The value is ${{ steps.step1.outputs.my_var }}"