name: 5_var_1_secrets
on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Monday  # Workflow level variable

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello  # Job level variable
    steps:
      - name: Use secret
        run: echo "Your secret is ${{ secrets.MY_SECRET }}"