name: 6_conditional_0

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Type of build to execute'
        required: true
        type: choice
        default: 'dev'
        options:
          - dev
          - tst
          - stg
          - prd
      include_test_case:
        description: 'Run tests during the build'
        required: false
        default: 'false'
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Generate value
        id: step1
        run: echo "buid- ${{ github.event.inputs.build_type }} testCase- ${{ github.event.inputs.include_test_case }}"
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Generate value
        #if: github.repository == 'my-org/prod-repo'
        if: github.event.inputs.build_type == 'prd'
        id: step1
        run: echo "production job running"
  
