name: 7_workflow_0_parent

on:
  workflow_call:
    inputs:
      input_username1:
          required: true
          type: string
      input_username2:
          type: string
          required: false
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Running tests"
          echo "username1- {{ inputs.input_username1 }} username2- {{ inputs.input_username2 }} "