name: 7_workflow_0_parent

on:
  workflow_call:
    inputs:
      username1:
          required: true
          type: string
      username2:
          type: string
          required: false
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Running tests"
          echo "username1- ${{ inputs.username1 }} username2- ${{ inputs.username2 }} "