name: 7_workflow_1_child

on:
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: cloud99ashwani/devops/.github/workflows/7_workflow_0_parent.yml@master
    with:
      username1: testUsername1
      username2: testUsername2
    secrets:
      username3: ${{ secrets.username3 }}